version: 2
updates:
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: 'docker'
      - versions: ['15.x']
