version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app:delegated
      - empty:/app/node_modules
    # Run an init inside the container that forwards signals
    # and reaps processes.
    init: true
    image: api_seed_dev
    container_name: api_seed_dev

# Don't bind the node_modules from the host
volumes:
  empty:
