version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: ./env/Dockerfile
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - ..:/app:delegated
      # Workaround to prevent host node_modules from getting mounted in container
      - notused:/app/node_modules
    image: api
    container_name: api

volumes:
  notused:
